on:
  workflow_call:

    inputs:
      runs-on:
        type: string
        description: |
          Stringified list for choosing github runners. The default is using the 
          self-hosted buildfarm, but for public repositories the public-hosted 
          runners must be used (for example ubuntu-latest).
        default: '["self-hosted", "buildfarm"]'
        required: false
      distributions:
        type: string
        description: |
          Stringified list of the ROS distributions the package(s) will be built 
          for.
        default: '["melodic"]'
        required: false
      packages:
        type: string
        description: |
          Stringified list of the packages that should be built. If not provided 
          default behavior will be to build all packages.
        default: '[]'
        required: false

    secrets:
      pat-token:
        required: true
      repo-user:
        required: true
      repo-pass:
        required: true

jobs:
  build:
    runs-on: ${{ fromJson(inputs.runs-on) }}
    name: Build
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}
      - name: Checkout SagaActions
        uses: actions/checkout@v3
        with:
          repository: SAGARobotics/SagaActions
          token: ${{ secrets.pat-token }}
          path: .github/SagaActions
          ref: optim
      - name: Run Build test
        uses: ./.github/SagaActions/beta/build
        with:
          rosdistro: melodic
          packages: ${{ inputs.packages }}
          repo-user: ${{ secrets.repo-user }}
          repo-pass: ${{ secrets.repo-pass }}
