on:
  workflow_call:
    inputs:
      distributions:
        type: choice
        options:
          - melodic
          - noetic
        description: |
          The ROS distributions the package(s) will be built for.
        required: true
      packages:
        type:
