on:
  workflow_call:
    inputs:
      ros-distributions:
        description: |
          Stringified list of ROS distributions the package(s) will be built for
        required: true
        default: melodic
        type: string
      package:
        description: |
          The package that the CI pipeline will run for
        required: true
        type: string

      catch-dir:
        description: |
          Path to catch test files from the package's directory
        default: disabled
        required: false
        type: string
      gtest-dir:
        description: |
          Path to directory where google test files exist, from the 
          package's directory
        default: disabled
        required: false
        type: string

    secrets:
      pat-token:
        required: true
      dev-apt-rw-user:
        required: true

jobs:
  unit-tests:
    runs-on: [self-hosted, buildfarm]
    name: Run unit/library tests

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}

      # - name: Checkout SagaActions
      #   uses: actions/checkout@v2
      #   with:
      #     repository: SAGARobotics/SagaActions
      #     token: ${{ secrets.pat-token }}
      #     path: .github/SagaActions

      - name: Catch
        if: ${{ inputs.catch-dir != 'disabled' }}
        run: |
          cd ${{ github.workspace }}/${{ inputs.package }}/${{ inputs.catch-dir }}
          g++ -std=c++11 -Wall -o catchtests *.cpp
          ./catchtests
        shell: bash

      - name: GTest
        if: ${{ inputs.gtest-dir != 'disabled' }}
        run: |
          echo "::warning::Support for Google's test suite is not yet implemented"
        shell: bash
