on:
  workflow_call:
    inputs:
      ros-distributions:
        description: |
          Stringified list of ROS distributions the package(s) will be built for
        required: true
        default: melodic
        type: string
      ros-package-name:
        description: |
          Stringified json list of packages to be released. Default behaviour will
          release all packages in the repository.
        required: false
        type: string
    secrets:
      pat-token:
        required: true
      dev-apt-rw-user:
        required: true

jobs:
  build:
    runs-on: [self-hosted, buildfarm]
    name: Build and release Debian package(s)

    strategy:
      matrix:
        ros-distro: ${{ fromJson(inputs.ros-distributions) }}

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}

      - name: Checkout SagaActions
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/SagaActions
          token: ${{ secrets.pat-token }}
          path: .github/SagaActions

      # - name: Prerelease-checks
      #   uses: ./.github/SagaActions/prerelease-check
      #   with:
      #     ros-package-name: ${{ inputs.ros-package-name }}
      #     repo-user: ${{ secrets.APT_READ_USER }}
      #     repo-pass: ${{ secrets.APT_READ_PASS }}

      # - name: Testing
      #   uses: ./.github/SagaActions/run-tests
      #   with:
      #     package-to-test: ${{ inputs.ros-package-name }}
      #     saga-deb-read-user: ${{ secrets.dev-apt-rw-user }}

      - name: Build .deb package
        id: build
        uses: ./.github/SagaActions/build-debian/${{ matrix.ros-distro }}
        with:
          package-to-build: ${{ inputs.ros-package-name }}
          saga-deb-read-user: ${{ secrets.dev-apt-rw-user }}

      # - name: Update saga-rosdep
      #   uses: ./.github/SagaActions/update-saga-rosdep
      #   with:
      #     debian-package-name: ${{ steps.build.outputs.deb_package_name }}
      #     ros-package-name: ${{ inputs.ros-package-name }}
      #     repo-token: ${{ secrets.pat-token }}

      # - name: Release package to repository
      #   id: apt-release
      #   uses: ./.github/SagaActions/push-package
      #   with:
      #     debian-package-name: ${{ steps.build.outputs.deb_package_name }}
      #     ros-package-name: ${{ inputs.ros-package-name }}
      #     repo-user: ${{ secrets.dev-apt-rw-user }}

      - name: Release
        uses: ./.github/SagaActions/release
        with:
          ros-distribution: ${{ matrix.ros-distro }}
          release-type: prod
          # package-name: ${{ inputs.ros-package-name }}
          # pat-token: ${{ secrets.pat-token }}
          # apt-user: ${{ secrets.dev-apt-rw-user }}
