on:
  workflow_call:
    inputs:
      ros-distributions:
        description: |
          Stringified list of ROS distributions the package(s) will be built for
        required: true
        default: melodic
        type: string
      packages:
        description: |
          Stringified list of ROS packages that this workflow will run for. Default
          behavior will release all packages in the repo.
          If a list is provided, only the packages defined in the list will be built.
        required: false
        default: 'release-all'
        type: string

      catch-dir:
        description: |
          Path to catch test files from the package's directory
        default: disabled
        required: false
        type: string
      gtest-dir:
        description: |
          Path to directory where google test files exist, from the 
          package's directory
        default: disabled
        required: false
        type: string
      no-rostests:
        description: | 
          Control parameter for running rostests. 
        default: false
        required: false
        type: boolean
      release-type:
        description: |
          Variable controlling where the produced package is released. Valid 
          values are "dev" (default) and "prod"
        default: 'dev'
        required: false
        type: string

    secrets:
      pat-token:
        required: true
      dev-apt-read-user:
        required: true
      dev-apt-read-write-user:
        required: true

jobs:
  create-matrix:
    runs-on: [self-hosted, buildfarm]
    name: Prepare Job matrix
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name:  Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}
      - name: Checkout SagaActions
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/SagaActions
          token: ${{ secrets.pat-token }}
          path: .github/SagaActions
      - name: Create matrix
        id: create-matrix
        uses: ./.github/SagaActions/create-matrix
        with: 
          pat-token: ${{ secrets.pat-token }}
          ros-distributions: ${{ inputs.ros-distributions }}
          packages: ${{ inputs.packages }}

  unit-tests:
    needs: create-matrix
    runs-on: [self-hosted, buildfarm]
    name: Unit tests

    strategy:
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}
      - name: Conform
        run: |
          if [[ -f package.xml ]];
          then
            mkdir ${{ github.event.repository.name }}
            mv `\ls -1 | grep -v ${{ github.event.repository.name }}` ${{ github.event.repository.name }}
          fi
        shell: bash

      - name: Catch
        if: ${{ inputs.catch-dir != 'disabled' }}
        run: |
          cd ${{ github.workspace }}/${{ matrix.package }}/${{ inputs.catch-dir }}
          g++ -std=c++11 -Wall -o catchtests *.cpp
          ./catchtests
        shell: bash

      - name: GTest
        if: ${{ inputs.gtest-dir != 'disabled' }}
        run: |
          echo "::warning::Support for Google's test suite is not yet implemented"
        shell: bash

  rostests:
    if: $${{ !inputs.no-rostests }}
    needs: create-matrix
    runs-on: [self-hosted, buildfarm]
    name: Integration tests

    strategy:
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}
      - name: Checkout SagaActions
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/SagaActions
          token: ${{ secrets.pat-token }}
          path: .github/SagaActions
      - name: Conform
        run: |
          if [[ -f package.xml ]];
          then
            mkdir ${{ github.event.repository.name }}
            mv `\ls -1 | grep -v ${{ github.event.repository.name }}` ${{ github.event.repository.name }}
          fi
        shell: bash

      - name: Rostests
        uses: ./.github/SagaActions/testing/rostests
        with:
          ros-distribution: ${{ matrix.ros-distro }}
          package-to-test: ${{ matrix.package }}
          saga-deb-read-user: ${{ secrets.dev-apt-read-user }}
          depend-repo: ${{ inputs.release-type }}

  build:
    needs: [unit-tests, rostests, create-matrix]
    runs-on: [self-hosted, buildfarm]
    name: Build Debian package

    strategy:
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}
      - name: Checkout SagaActions
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/SagaActions
          token: ${{ secrets.pat-token }}
          path: .github/SagaActions
      - name: Conform
        run: |
          if [[ -f package.xml ]];
          then
            mkdir ${{ github.event.repository.name }}
            mv `\ls -1 | grep -v ${{ github.event.repository.name }}` ${{ github.event.repository.name }}
          fi
        shell: bash

      # - name: Prerelease-checks
      #   uses: ./.github/SagaActions/prerelease-check
      #   with:
      #     ros-package-name: ${{ inputs.package }}
      #     repo-user: ${{ secrets.dev-apt-read-user }}
      - name: Build .deb package
        id: build
        uses: ./.github/SagaActions/build-debian
        with:
          ros-distribution: ${{ matrix.ros-distro }}
          package-to-build: ${{ matrix.package }}
          saga-deb-read-user: ${{ secrets.dev-apt-read-user }}
          release-type: ${{ inputs.release-type }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.package }}-${{ matrix.ros-distro }}-artifact
          path: ${{ github.workspace }}/${{ matrix.package }}/bin/${{ steps.build.outputs.deb_package_name }}
          if-no-files-found: error
          retention-days: 1

  release:
    needs: [build, create-matrix]
    runs-on: [self-hosted, buildfarm]
    name: Upload

    strategy:
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}
      - name: Checkout SagaActions
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/SagaActions
          token: ${{ secrets.pat-token }}
          path: .github/SagaActions

      - name: Download artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.package }}-${{ matrix.ros-distro }}-artifact
          path: ${{ github.workspace }}/artifacts/${{ matrix.ros-distro }}

      - name: Find debian filename
        id: name
        run: |
          echo "Artifacts:"
          ls ${{ steps.download.outputs.download-path }}
          DEBFILE=$(ls ${{ steps.download.outputs.download-path }} | grep -e "\.deb$")
          echo "::set-output name=debfile::$DEBFILE"
        shell: bash

      - name: Release package to repository
        id: apt-release
        uses: ./.github/SagaActions/push-package
        with:
          debian-package-name: ${{ steps.name.outputs.debfile }}
          package-location: ${{ steps.download.outputs.download-path }}
          ros-package-name: ${{ matrix.package }}
          repo-user: ${{ secrets.dev-apt-read-write-user }}
          release-type: ${{ inputs.release-type }}

      - name: Update saga-rosdep
        uses: ./.github/SagaActions/update-saga-rosdep
        with:
          debian-package-name: ${{ steps.name.outputs.debfile }}
          ros-package-name: ${{ matrix.package }}
          repo-token: ${{ secrets.pat-token }}
          release-type: ${{ inputs.release-type }}
