on:
  workflow_call:
    inputs:
      ros-distributions:
        description: |
          Stringified list of ROS distributions the package(s) will be built for
        required: true
        default: melodic
        type: string
      packages:
        description: |
          Stringified list of ROS packages that this workflow will run for. Default
          behavior will release all packages in the repo, or, if the repository contains
          a single package, release the one package that the repository contains.
          If a list is provided, only the packages defined in the list will be built.
        required: false
        default: 'release-all'
        type: string

      catch-dir:
        description: |
          Path to catch test files from the package's directory
        default: disabled
        required: false
        type: string
      gtest-dir:
        description: |
          Path to directory where google test files exist, from the 
          package's directory
        default: disabled
        required: false
        type: string
      no-rostests:
        description: | 
          Control parameter for running rostests. 
        default: false
        required: false
        type: boolean
      release-type:
        description: |
          Variable controlling where the produced package is released. Valid 
          values are "dev" (default) and "prod"
        default: 'dev'
        required: false
        type: string

    secrets:
      pat-token:
        required: true
      dev-apt-read-user:
        required: true
      dev-apt-read-write-user:
        required: true

jobs:
  prepare-repo:
    runs-on: [self-hosted, buildfarm]
    name: Prepare Repository
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}
      - name: Checkout SagaActions
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/SagaActions
          token: ${{ secrets.pat-token }}
          path: .github/SagaActions

      - name: Create matrix
        id: create-matrix
        uses: ./.github/SagaActions/prepare-repo
        with: 
          pat-token: ${{ secrets.pat-token }}
          ros-distributions: ${{ inputs.ros-distributions }}
    
  test-output:
    needs: prepare-repo
    runs-on: [self-hosted, buildfarm]
    strategy:
      matrix: ${{ fromJson(needs.prepare-repo.outputs.matrix) }}

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/${{ github.event.repository.name }}
          token: ${{ secrets.pat-token }}
      - name: Checkout SagaActions
        uses: actions/checkout@v2
        with:
          repository: SAGARobotics/SagaActions
          token: ${{ secrets.pat-token }}
          path: .github/SagaActions

      - name: Prepare repository
        id: prep
        uses: ./.github/SagaActions/prepare-repo
        with: 
          pat-token: ${{ secrets.pat-token }}
          ros-distributions: ${{ inputs.ros-distributions }}
      - name: Test JOB
        run: echo ${{ needs.prepare-repo.outputs.matrix }}
      - name: Test STEP
        run: echo ${{ steps.prep.outputs.matrix }}
        
      - run: echo ${{ matrix.ros-distro }}
      - run: echo ${{ matrix.package }}

